config/routes.rb
TasteSpottingClone::Application.routes.draw do
  resources :users, :only => [:create, :new, :show, :index]
  resource :session, :only => [:create, :destroy, :new]
  resources :posts
  resources :categories, :only => [:create, :edit, :index]
  resources :favorites, :only => [:create, :edit, :index, :destroy]

  root :to => "roots#root"
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :post_ids
  
  has_many :memberships,
  :class_name => "CategoryMembership",
  :foreign_key => :category_id,
  :primary_key => :id
  
  has_many :members,
  :through => :memberships,
  :source => :post
end

app/models/category_membership.rb
class CategoryMembership < ActiveRecord::Base
  attr_accessible :category_id, :post_id
  
  belongs_to :category,
  :class_name => "Category",
  :foreign_key => :category_id,
  :primary_key => :id
  
  belongs_to :post,
  :class_name => "Post",
  :foreign_key => :post_id,
  :primary_key => :id
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  attr_accessible :post_id, :user_id
  
  belongs_to :user,
  :class_name => "User",
  :foreign_key => :user_id,
  :primary_key => :id
  
  belongs_to :post,
  :class_name => "Post",
  :foreign_key => :post_id,
  :primary_key => :id
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible(
    :description,
    :link,
    :submitter_id,
    :post_photo,
    :category_ids
    )
  
  validates(
    :description,
    :link,
    :submitter_id,
    :presence => true
    )
  
  belongs_to :user,
  :class_name => "User",
  :foreign_key => :submitter_id,
  :primary_key => :id
  
  has_many :memberships,
  :class_name => "CategoryMembership",
  :foreign_key => :post_id,
  :primary_key => :id
  
  has_many :categories,
  :through => :memberships,
  :source => :category
  
  has_many :favorites,
  :class_name => "Favorite",
  :foreign_key => :post_id,
  :primary_key => :id
  
  has_attached_file :post_photo, :styles => {
    # use # after dimensions to scale and crop.
    # use > after dimenstions to scale
    :medium => "250x250#"
  }
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password
  attr_reader :password

  validates :password_digest, :presence => { :message => "Password can't be blank" }
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :presence => true
  validates :username, :presence => true

  after_initialize :ensure_session_token

  has_many :posts,
  :class_name => "Post",
  :foreign_key => :submitter_id,
  :primary_key => :id
  
  has_many :favorites,
  :class_name => "Favorite",
  :foreign_key => :user_id,
  :primary_key => :id

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)

    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def index
    @categories = Category.all
    respond_to do |format|
      format.json { render :json => @categories }
    end
  end
  
  def create
    @category = Category.create!(params[:category])
    render :json => @category 
  end
  
  def update
    @category = Category.find_by_id(params[:id])
    @category.update_attributes!(params[:category])
    render :json => @category
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def index
    @favorites = Favorite.all
    respond_to do |format|
      format.json { render :json => @favorites }
    end
  end
  
  def create
    @favorite = Favorite.create!(params[:favorite])
    render :json => @favorite
  end
  
  def update
    @favorite = Favorite.find_by_id(params[:id])
    @favorite.update_attributes!(params[:favorite])
    render :json => @favorite
  end
  
  def destroy
    @favorite = Favorite.find_by_id(params[:id])
    @favorite.destroy
    render :json => @post
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :require_current_user!, :only => [:new, :create]
  
  def index
    @posts = Post.all
    respond_to do |format|
      format.json { render "index.rabl" }
    end
  end

  def new
    @post = Post.new()
    render :json => @post
  end
  
  def create
    @post = Post.new(params[:post])
    @post.submitter_id = current_user.id
    if @post.save
      render "create.rabl"
    else
      render :new
    end
  end

  def show
    @post = Post.find_by_id(params[:id])
    render :show
  end
  
  def update
    @post = Post.find_by_id(params[:id])
    if current_user.id == @post.submitter_id
      @post.update_attributes!(params[:post])
    end
    render "create.rabl"
  end
  
  def destroy
    @post = Post.find_by_id(params[:id])
    if current_user.id == @post.submitter_id
      @post.destroy
    end
    render :json => @post
  end
  
end

app/controllers/roots_controller.rb
class RootsController < ApplicationController

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :require_no_current_user!, :only => [:create, :new]
  before_filter :require_current_user!, :only => [:destroy]

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user.nil?
      render :json => "Credentials were wrong"
    else
      self.current_user = user
      redirect_to root_url
    end
  end

  def destroy
    logout_current_user!
    redirect_to new_session_url
  end

  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_current_user!, :only => [:show]
  before_filter :require_no_current_user!, :only => [:create, :new]

  def index
    @users = User.all
    @current_user = current_user
    respond_to do |format|
      format.json { render "index.rabl" }
    end
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      self.current_user = @user
      redirect_to root_url
    else
      render :json => @user.errors.full_messages
    end
  end

  def new
    @user = User.new
  end
 
  # def show
  #   if params.include?(:id)
  #     @posts = Post.where(submitter_id: params[:id])
  #     @user = User.find(params[:id])
  #     render :json => @user
  #   else
  #     redirect_to user_url(current_user)
  #   end
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def current_user=(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def logout_current_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_current_user!
    redirect_to new_session_url if current_user.nil?
  end

  def require_no_current_user!
    redirect_to user_url(current_user) unless current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasty Bite</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link
    href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" 
    rel="stylesheet">
</head>
<body>
  <div>
    <div class="container">
      <div class="four columns sidebar">
        <% if !current_user.nil? %>
        <p>
            <%= current_user.username %>
            <%= link_to('Logout', session_url, :method => :delete) %>
        </p>
        <% end %>
      </div>
    </div>
  </div>
  <div>
    <div class="container">
      <div class="four columns sidebar">

      </div>
      <div class="sixteen columns offset-by-one content">

      </div>
    </div>
  </div>
  <div>
    <div class="container">
      <div class="three columns sidebar">
        <h2>Tasty Bite</h2>
        <hr>
        <ul>
        <% if !current_user.nil? %>
          <strong>
          <li><%= link_to("Post Index", "#/") %></li>
          <li><%= link_to("Users", "#users") %></li>
          <li><%= link_to("New Post", "#posts/new") %></li>
          </strong>
        <% else %>
          <strong>
          <li><%= link_to("Post Index", root_url) %></li>
          <li><%= link_to("Sign up", new_user_url)%></li>
          <li><%= link_to("Log in", new_session_url)%></li>
          </strong>
        <% end %>
        <br>
        <hr>
        <li><h4>Categories:</h4></li>

        <% Category.all.each do |category| %></li>
          <strong>
          <li>
            <%= link_to("#{category.name}",
                        root_url + "#category/#{category.id}" )%>
          </li>
          </strong>
        <% end %>
        </ul>
      </div>
      <div class="sixteen columns offset-by-one content">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/new.html.erb
<h2>Create a new post</h2>

<!-- <%= form_for @post do |f| %>
  <%= f.file_field :post_photo %><br><br>
  
  <%= f.label :link %>:<br>
  <%= f.text_field :link %><br><br>

  <%= f.label :description %>:<br>
  <%= f.text_field :description %><br><br>

  <%= f.submit %>
<% end %> -->

<form action="<%= posts_url %>" method="post" enctype="multipart/form-data">
  <input
    name="authenticity_token"
    type="hidden"
    value="<%= form_authenticity_token %>">

  <label for="post_post_photo">Image</label>
  <br>  
  <input
    type="file"
    name="post[post_photo]"
    id="post_post_photo">

  <br>
  <label for="post_link">Link</label>
  <br>
  <input
    type="text"
    name="post[link]"
    id="post_link">

  <br>
  <label for="post_description">Description</label>
  <br>
  <input
    type="text"
    name="post[description]"
    id="post_description">

  <br>
  <input type="submit" value="Create Post">
</form>

app/views/posts/show.html.erb
<h2>Post</h2>

<div>
  <%= image_tag @post.post_photo.url(:medium) %><br>
  <%= link_to(@post.description, @post.link)%><br>
</div>

app/views/roots/root.html.erb
<div id="content"></div>

app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "put" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create user") %>

<form action="<%= action %>" method="post">
  <input
    name="_method"
    type="hidden"
    value="<%= method %>">
  <input
    name="authenticity_token"
    type="hidden"
    value="<%= form_authenticity_token %>">

  <label for="user_username">Username</label>
  <input
    id="user_username"
    name="user[username]"
    type="text">

  <label for="user_password">Password</label>
  <input
    id="user_password"
    name="user[password]"
    type="password">

  <input
    type="submit"
    value="<%= message %>">
</form>

app/views/users/index.html.erb
<h2>All users</h2>

<ol>
  <% @users.each do |user| %>
    <li><%= link_to(user.username, user_url(user.id)) %></li>
  <% end %>
</ol>

app/views/users/new.html.erb
<h2>
  Create an account
</h2>

<p>Please enter a password longer than 6 characters.</p>
<%= render "form", :user => @user %>

app/views/users/show.html.erb
<h2>
  <%= @user.username %>'s profile
</h2>

<p>Posts</p>
<div>
  <% @posts.each do |post| %>
    <%= image_tag post.post_photo.url(:medium) %><br>
    <%= link_to(post.description, post.link)%><br>
  <% end %>
</div>